import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:stock_quant_app/data/models/order.dart';
import 'package:stock_quant_app/domain/enums/order_enums.dart';
import 'package:stock_quant_app/presentation/controllers/order_controller.dart';

/// Order entry form widget for creating new orders
class OrderEntry extends ConsumerStatefulWidget {
  const OrderEntry({super.key});

  @override
  ConsumerState<OrderEntry> createState() => _OrderEntryState();
}

class _OrderEntryState extends ConsumerState<OrderEntry> {
  final _formKey = GlobalKey<FormState>();
  final _symbolController = TextEditingController();
  final _priceController = TextEditingController();
  final _quantityController = TextEditingController();
  OrderType _selectedType = OrderType.market;
  OrderSide _selectedSide = OrderSide.buy;

  @override
  void dispose() {
    _symbolController.dispose();
    _priceController.dispose();
    _quantityController.dispose();
    super.dispose();
  }

  void _handleSubmit() {
    if (_formKey.currentState!.validate()) {
      final order = Order(
        id: DateTime.now()
            .toString(), // Temporary ID, should be generated by backend
        symbol: _symbolController.text,
        type: _selectedType,
        side: _selectedSide,
        price: double.parse(_priceController.text),
        quantity: double.parse(_quantityController.text),
        status: OrderStatus.pending,
        createdAt: DateTime.now(),
      );

      ref.read(orderListProvider.notifier).createOrder(order);
      _resetForm();
    }
  }

  void _resetForm() {
    _symbolController.clear();
    _priceController.clear();
    _quantityController.clear();
    setState(() {
      _selectedType = OrderType.market;
      _selectedSide = OrderSide.buy;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        children: [
          TextFormField(
            controller: _symbolController,
            decoration: const InputDecoration(labelText: 'Symbol'),
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a symbol';
              }
              return null;
            },
          ),
          DropdownButtonFormField<OrderType>(
            value: _selectedType,
            decoration: const InputDecoration(labelText: 'Order Type'),
            items: OrderType.values.map((type) {
              return DropdownMenuItem(
                value: type,
                child: Text(type.displayName),
              );
            }).toList(),
            onChanged: (value) {
              setState(() {
                _selectedType = value!;
              });
            },
          ),
          DropdownButtonFormField<OrderSide>(
            value: _selectedSide,
            decoration: const InputDecoration(labelText: 'Side'),
            items: const [
              DropdownMenuItem(
                value: OrderSide.buy,
                child: Text('Buy'),
              ),
              DropdownMenuItem(
                value: OrderSide.sell,
                child: Text('Sell'),
              ),
            ],
            onChanged: (value) {
              setState(() {
                _selectedSide = value!;
              });
            },
          ),
          TextFormField(
            controller: _priceController,
            decoration: const InputDecoration(labelText: 'Price'),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a price';
              }
              if (double.tryParse(value) == null) {
                return 'Please enter a valid number';
              }
              return null;
            },
          ),
          TextFormField(
            controller: _quantityController,
            decoration: const InputDecoration(labelText: 'Quantity'),
            keyboardType: TextInputType.number,
            validator: (value) {
              if (value == null || value.isEmpty) {
                return 'Please enter a quantity';
              }
              if (double.tryParse(value) == null) {
                return 'Please enter a valid number';
              }
              return null;
            },
          ),
          const SizedBox(height: 16),
          ElevatedButton(
            onPressed: _handleSubmit,
            child: const Text('Submit Order'),
          ),
        ],
      ),
    );
  }
}
