// Mocks generated by Mockito 5.4.5 from annotations
// in stock_quant_app/test/mocks/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stock_quant_app/data/models/market_data.dart' as _i6;
import 'package:stock_quant_app/domain/entities/stock_entity.dart' as _i2;
import 'package:stock_quant_app/domain/repositories/market_repository.dart'
    as _i3;
import 'package:stock_quant_app/domain/services/websocket_service.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStockEntity_0 extends _i1.SmartFake implements _i2.StockEntity {
  _FakeStockEntity_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MarketRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMarketRepository extends _i1.Mock implements _i3.MarketRepository {
  MockMarketRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.StockEntity>> getStocks() => (super.noSuchMethod(
        Invocation.method(
          #getStocks,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.StockEntity>>.value(<_i2.StockEntity>[]),
      ) as _i4.Future<List<_i2.StockEntity>>);

  @override
  _i4.Future<_i2.StockEntity> getStock(String? symbol) => (super.noSuchMethod(
        Invocation.method(
          #getStock,
          [symbol],
        ),
        returnValue: _i4.Future<_i2.StockEntity>.value(_FakeStockEntity_0(
          this,
          Invocation.method(
            #getStock,
            [symbol],
          ),
        )),
      ) as _i4.Future<_i2.StockEntity>);

  @override
  _i4.Future<Map<String, dynamic>> getMarketOverview() => (super.noSuchMethod(
        Invocation.method(
          #getMarketOverview,
          [],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i2.StockEntity>> getHotStocks() => (super.noSuchMethod(
        Invocation.method(
          #getHotStocks,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.StockEntity>>.value(<_i2.StockEntity>[]),
      ) as _i4.Future<List<_i2.StockEntity>>);

  @override
  _i4.Future<List<_i2.StockEntity>> getWatchlist() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlist,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.StockEntity>>.value(<_i2.StockEntity>[]),
      ) as _i4.Future<List<_i2.StockEntity>>);

  @override
  _i4.Future<void> addToWatchlist(String? symbol) => (super.noSuchMethod(
        Invocation.method(
          #addToWatchlist,
          [symbol],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromWatchlist(String? symbol) => (super.noSuchMethod(
        Invocation.method(
          #removeFromWatchlist,
          [symbol],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i5.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> connect() => (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i6.MarketData> subscribeToMarketData(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToMarketData,
          [symbol],
        ),
        returnValue: _i4.Stream<_i6.MarketData>.empty(),
      ) as _i4.Stream<_i6.MarketData>);

  @override
  _i4.Future<void> unsubscribeFromMarketData(String? symbol) =>
      (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromMarketData,
          [symbol],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
